[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
evm_version = "cancun"  # hard fork that enabled EIP-1153
optimizer_runs = 800
via_ir = false
ffi = true

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
polygonMumbai = "${POLYGON_MUMBAI_RPC_URL}"
bnbChainTestnet = "${BNB_CHAIN_TESTNET_RPC_URL}"
baseGoerli = "${BASE_GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config