[profile.default]
src = "contracts"
out = "out"
libs = ["../../lib", "../../contracts/src"]
test = "tests"
ffi = true

fs_permissions = [{ access = "read-write", path = "./"}]


gas_reports = ["*"]

# A list of ignored solc error codes

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config